In [1]:
import numpy as np
import pandas as pd

In [3]:
array = []
for i in range(1,17):
    array.append(pd.read_csv('TAXRATES'+str(i)+'.csv',names=['State']))

In [4]:
new_csv = pd.concat(array)
new_csv.to_csv('AllTask.csv')

In [8]:
new_csv

State    RiskLevel
Name: (State, ZipCode, TaxRegionName, StateRate, EstimatedCombinedRate, EstimatedCountyRate, EstimatedCityRate, EstimatedSpecialRate), dtype: object

In [5]:
csv1 = new_csv.loc[:,['State','ZipCode','EstimatedCombinedRate']]

In [14]:
csv1 = csv1.sort_values(by='ZipCode')
csv1

    State  ZipCode  EstimatedCombinedRate
0      CT     6001                 0.0635
1      CT     6002                 0.0635
2      CT     6006                 0.0635
3      CT     6010                 0.0635
4      CT     6011                 0.0635
5      CT     6013                 0.0635
6      CT     6016                 0.0635
7      CT     6018                 0.0635
8      CT     6019                 0.0635
9      CT     6020                 0.0635
10     CT     6021                 0.0635
11     CT     6022                 0.0635
12     CT     6023                 0.0635
13     CT     6024                 0.0635
14     CT     6025                 0.0635
15     CT     6026                 0.0635
16     CT     6027                 0.0635
17     CT     6028                 0.0635
18     CT     6029                 0.0635
19     CT     6030                 0.0635
20     CT     6031                 0.0635
21     CT     6032                 0.0635
22     CT     6033                 0.0635
23     CT     6034                 0.0635
24     CT     6035                 0.0635
25     CT     6037                 0.0635
26     CT     6039                 0.0635
27     CT     6040                 0.0635
28     CT     6041                 0.0635
29     CT     6042                 0.0635
..    ...      ...                    ...
241    AK    99811                 0.0500
242    AK    99812                 0.0500
243    AK    99820                 0.0300
244    AK    99821                 0.0500
245    AK    99824                 0.0500
246    AK    99825                 0.0000
247    AK    99826                 0.0300
248    AK    99827                 0.0400
249    AK    99829                 0.0650
250    AK    99830                 0.0500
251    AK    99832                 0.0400
252    AK    99833                 0.0600
253    AK    99835                 0.0500
254    AK    99836                 0.0500
255    AK    99840                 0.0300
256    AK    99841                 0.0200
257    AK    99850                 0.0500
258    AK    99901                 0.0650
259    AK    99903                 0.0650
260    AK    99918                 0.0650
261    AK    99919                 0.0650
262    AK    99921                 0.0500
263    AK    99922                 0.0600
264    AK    99923                 0.0000
265    AK    99925                 0.0650
266    AK    99926                 0.0000
267    AK    99927                 0.0000
268    AK    99928                 0.0250
269    AK    99929                 0.0700
270    AK    99950                 0.0650

[12768 rows x 3 columns]

In [17]:
new_csv.sort_values(['ZipCode','EstimatedCombinedRate'])

,State,ZipCode,TaxRegionName,StateRate,EstimatedCombinedRate,EstimatedCountyRate,EstimatedCityRate,EstimatedSpecialRate,RiskLevel
0,CT,6001,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
1,CT,6002,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
2,CT,6006,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
3,CT,6010,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
4,CT,6011,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
5,CT,6013,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
6,CT,6016,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
7,CT,6018,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
8,CT,6019,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
9,CT,6020,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
10,CT,6021,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
11,CT,6022,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
12,CT,6023,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
13,CT,6024,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
14,CT,6025,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
15,CT,6026,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
16,CT,6027,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
17,CT,6028,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
18,CT,6029,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
19,CT,6030,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
20,CT,6031,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
21,CT,6032,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
22,CT,6033,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
23,CT,6034,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
24,CT,6035,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
25,CT,6037,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
26,CT,6039,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
27,CT,6040,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
28,CT,6041,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
29,CT,6042,CONNECTICUT STATE,0.0635,0.0635,0.000,0.000,0.0,0
...,...,...,...,...,...,...,...,...,...
241,AK,99811,JUNEAU BURROUGH,0.0000,0.0500,0.050,0.000,0.0,1
242,AK,99812,JUNEAU BURROUGH,0.0000,0.0500,0.050,0.000,0.0,1
243,AK,99820,ANGOON,0.0000,0.0300,0.000,0.030,0.0,1
244,AK,99821,JUNEAU BURROUGH,0.0000,0.0500,0.050,0.000,0.0,2
245,AK,99824,JUNEAU BURROUGH,0.0000,0.0500,0.050,0.000,0.0,2
246,AK,99825,ALASKA STATE,0.0000,0.0000,0.000,0.000,0.0,1
247,AK,99826,GUSTAVUS,0.0000,0.0300,0.000,0.030,0.0,1
248,AK,99827,HAINES BURROUGH,0.0000,0.0400,0.040,0.000,0.0,1
249,AK,99829,HOONAH,0.0000,0.0650,0.000,0.065,0.0,1
250,AK,99830,KAKE,0.0000,0.0500,0.000,0.050,0.0,1
251,AK,99832,PELICAN,0.0000,0.0400,0.000,0.040,0.0,1
252,AK,99833,PETERSBURG BOROUGH,0.0000,0.0600,0.060,0.000,0.0,2
253,AK,99835,SITKA BURROUGH,0.0000,0.0500,0.050,0.000,0.0,1
254,AK,99836,SITKA BURROUGH,0.0000,0.0500,0.050,0.000,0.0,2
255,AK,99840,SKAGWAY,0.0000,0.0300,0.000,0.030,0.0,1
256,AK,99841,TENAKEE SPRINGS,0.0000,0.0200,0.000,0.020,0.0,1
257,AK,99850,JUNEAU BURROUGH,0.0000,0.0500,0.050,0.000,0.0,1
258,AK,99901,KETCHIKAN,0.0000,0.0650,0.000,0.065,0.0,7
259,AK,99903,KETCHIKAN,0.0000,0.0650,0.000,0.065,0.0,4
260,AK,99918,KETCHIKAN,0.0000,0.0650,0.000,0.065,0.0,4
261,AK,99919,KETCHIKAN,0.0000,0.0650,0.000,0.065,0.0,4
262,AK,99921,CRAIG,0.0000,0.0500,0.000,0.050,0.0,1
263,AK,99922,HYDABURG,0.0000,0.0600,0.000,0.060,0.0,1
264,AK,99923,ALASKA STATE,0.0000,0.0000,0.000,0.000,0.0,1
265,AK,99925,KLAWOCK,0.0000,0.0650,0.000,0.065,0.0,1
266,AK,99926,ALASKA STATE,0.0000,0.0000,0.000,0.000,0.0,1
267,AK,99927,ALASKA STATE,0.0000,0.0000,0.000,0.000,0.0,1
268,AK,99928,KETCHIKAN GATEWAY BURROUGH,0.0000,0.0250,0.025,0.000,0.0,1
269,AK,99929,WRANGELL,0.0000,0.0700,0.000,0.070,0.0,1
270,AK,99950,KETCHIKAN,0.0000,0.0650,0.000,0.065,0.0,5

In [18]:
new_csv[new_csv['EstimatedCombinedRate'].isin([0.070]) & new_csv['State'].isin(['AK'])]

,State,ZipCode,TaxRegionName,StateRate,EstimatedCombinedRate,EstimatedCountyRate,EstimatedCityRate,EstimatedSpecialRate,RiskLevel
81,AK,99615,KODIAK,0.0,0.07,0.0,0.07,0.0,3
82,AK,99619,KODIAK,0.0,0.07,0.0,0.07,0.0,1
156,AK,99697,KODIAK,0.0,0.07,0.0,0.07,0.0,1
269,AK,99929,WRANGELL,0.0,0.07,0.0,0.07,0.0,1

In [19]:
estimated = new_csv.EstimatedCombinedRate.unique()
estimated

array([0.      , 0.03    , 0.04    , 0.05    , 0.02    , 0.06    ,
       0.035   , 0.0785  , 0.07    , 0.065   , 0.01    , 0.025   ,
       0.1     , 0.09    , 0.085   , 0.08    , 0.0875  , 0.095   ,
       0.055   , 0.075   , 0.07625 , 0.105   , 0.0775  , 0.11    ,
       0.115   , 0.0975  , 0.1125  , 0.10375 , 0.1075  , 0.08625 ,
       0.09625 , 0.0925  , 0.1025  , 0.0825  , 0.09125 , 0.08125 ,
       0.08375 , 0.086   , 0.063   , 0.096   , 0.072   , 0.092   ,
       0.0855  , 0.102   , 0.112   , 0.083   , 0.078   , 0.0805  ,
       0.088   , 0.0795  , 0.089   , 0.081   , 0.061   , 0.0635  ,
       0.076   , 0.093   , 0.06712 , 0.098   , 0.101   , 0.10712 ,
       0.09212 , 0.0835  , 0.08412 , 0.066   , 0.091   , 0.087   ,
       0.106   , 0.069   , 0.08951 , 0.0885  , 0.109   , 0.099   ,
       0.0918  , 0.1035  , 0.0935  , 0.0985  , 0.104   , 0.0585  ,
       0.0725  , 0.07975 , 0.08975 , 0.08475 , 0.08725 , 0.07375 ,
       0.07875 , 0.08875 , 0.0796  , 0.0815  , 0.0475  , 0.04985 ,
       0.08485 , 0.08635 , 0.0675  , 0.039   , 0.0375  , 0.0325  ,
       0.079   , 0.0513  , 0.0831  , 0.068125, 0.0713  , 0.08845 ,
       0.045   , 0.029   , 0.044   , 0.06375 , 0.0455  , 0.0955  ,
       0.049   , 0.0905  , 0.082   , 0.042   , 0.0755  , 0.084   ,
       0.059   , 0.08515 , 0.037   , 0.074   , 0.054   , 0.067   ,
       0.05985 , 0.0685  , 0.064   , 0.0701  , 0.0788  , 0.0813  ,
       0.0873  , 0.0799  , 0.094   , 0.0865  , 0.0565  , 0.0765  ,
       0.0735  , 0.033   , 0.0465  , 0.0415  , 0.0945  , 0.0545  ,
       0.0802  , 0.0527  , 0.0827  , 0.0727  , 0.0425  , 0.0625  ,
       0.071   ])

In [20]:
uniqueState = new_csv.State.unique()
uniqueState

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN'], dtype=object)

In [21]:
arrayData = []
for estimate in estimated:
    for state in uniqueState:
        fil = csv1[csv1['EstimatedCombinedRate'].isin([estimate]) & csv1['State'].isin([state])]
        if len(fil) != 0:
            obj = {
                'to_postcode_ taxrate': fil.ZipCode.max(),
                'from_postcode': fil.ZipCode.min(),
                'EstimatedCombinedRate': estimate,
                'state': state
            }
#             print(obj)
            arrayData.append(obj)
# new_csv[new_csv['EstimatedCombinedRate'].isin([0.0]) & new_csv['State'].isin(['AK'])]
# new_csv[new_csv['EstimatedCombinedRate'].isin(estimated) & new_csv['State'].isin(uniqueState)]

In [25]:
# arrayData
new_csv[new_csv['EstimatedCombinedRate'].isin(estimated) & new_csv['State'].isin(uniqueState)]

,State,ZipCode,TaxRegionName,StateRate,EstimatedCombinedRate,EstimatedCountyRate,EstimatedCityRate,EstimatedSpecialRate,RiskLevel
0,AK,99501,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
1,AK,99502,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
2,AK,99503,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
3,AK,99504,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
4,AK,99505,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
5,AK,99506,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
6,AK,99507,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
7,AK,99508,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
8,AK,99509,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
9,AK,99510,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
10,AK,99511,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
11,AK,99513,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
12,AK,99514,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
13,AK,99515,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
14,AK,99516,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
15,AK,99517,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
16,AK,99518,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
17,AK,99519,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
18,AK,99520,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
19,AK,99521,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
20,AK,99522,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
21,AK,99523,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
22,AK,99524,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
23,AK,99529,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
24,AK,99530,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,1
25,AK,99540,ANCHORAGE BOROUGH,0.00,0.00,0.0,0.00,0.0,3
26,AK,99546,COLD BAY,0.00,0.00,0.0,0.00,0.0,1
27,AK,99547,UNALASKA,0.00,0.03,0.0,0.03,0.0,1
28,AK,99548,CHIGNIK,0.00,0.00,0.0,0.00,0.0,1
29,AK,99549,BRISTOL BAY BOROUGH,0.00,0.00,0.0,0.00,0.0,1
...,...,...,...,...,...,...,...,...,...
923,IN,47960,WHITE,0.07,0.07,0.0,0.00,0.0,0
924,IN,47962,TIPPECANOE,0.07,0.07,0.0,0.00,0.0,0
925,IN,47963,NEWTON,0.07,0.07,0.0,0.00,0.0,0
926,IN,47964,MOUNT AYR,0.07,0.07,0.0,0.00,0.0,0
927,IN,47965,NEW MARKET,0.07,0.07,0.0,0.00,0.0,0
928,IN,47966,NEWPORT,0.07,0.07,0.0,0.00,0.0,0
929,IN,47967,MONTGOMERY,0.07,0.07,0.0,0.00,0.0,0
930,IN,47968,MONTGOMERY,0.07,0.07,0.0,0.00,0.0,0
931,IN,47969,NEWTOWN,0.07,0.07,0.0,0.00,0.0,0
932,IN,47970,WARREN,0.07,0.07,0.0,0.00,0.0,0
933,IN,47971,OXFORD,0.07,0.07,0.0,0.00,0.0,0
934,IN,47974,VERMILLION,0.07,0.07,0.0,0.00,0.0,0
935,IN,47975,WARREN,0.07,0.07,0.0,0.00,0.0,0
936,IN,47977,REMINGTON,0.07,0.07,0.0,0.00,0.0,0
937,IN,47978,RENSSELAER,0.07,0.07,0.0,0.00,0.0,0
938,IN,47980,WHITE,0.07,0.07,0.0,0.00,0.0,0
939,IN,47981,TIPPECANOE,0.07,0.07,0.0,0.00,0.0,0
940,IN,47982,LAFAYETTE,0.07,0.07,0.0,0.00,0.0,0
941,IN,47983,TIPPECANOE,0.07,0.07,0.0,0.00,0.0,0
942,IN,47986,BENTON,0.07,0.07,0.0,0.00,0.0,0
943,IN,47987,VEEDERSBURG,0.07,0.07,0.0,0.00,0.0,0
944,IN,47989,MONTGOMERY,0.07,0.07,0.0,0.00,0.0,0
945,IN,47990,MONTGOMERY,0.07,0.07,0.0,0.00,0.0,0
946,IN,47991,WEST LEBANON,0.07,0.07,0.0,0.00,0.0,0
947,IN,47992,TIPPECANOE,0.07,0.07,0.0,0.00,0.0,0
948,IN,47993,WILLIAMSPORT,0.07,0.07,0.0,0.00,0.0,0
949,IN,47994,MONTGOMERY,0.07,0.07,0.0,0.00,0.0,0
950,IN,47995,WHITE,0.07,0.07,0.0,0.00,0.0,0
951,IN,47996,WEST LAFAYETTE,0.07,0.07,0.0,0.00,0.0,0
952,IN,47997,YEOMAN,0.07,0.07,0.0,0.00,0.0,0

In [144]:
allData = pd.DataFrame(arrayData)
allData

     EstimatedCombinedRate  from_postcode state  to_postcode_ taxrate
0                  0.00000          99501    AK                 99927
1                  0.00000          19701    DE                 19980
2                  0.03000          99547    AK                 99840
3                  0.04000          99554    AK                 99832
4                  0.04000          80116    CO                 80135
5                  0.04000          96708    HI                 96793
6                  0.05000          99555    AK                 99921
7                  0.05000          35032    AL                 36866
8                  0.05000          80126    CO                 80163
9                  0.02000          99557    AK                 99841
10                 0.06000          99559    AK                 99922
11                 0.06000          35006    AL                 36853
12                 0.06000          20001    DC                 88888
13                 0.06000          34423    FL                 34487
14                 0.06000          30003    GA                 31144
15                 0.06000          50007    IA                 52351
16                 0.06000          83201    ID                 83877
17                 0.03500          99591    AK                 99660
18                 0.07850          99603    AK                 99603
19                 0.07850          86403    AZ                 86442
20                 0.07850          62002    IL                 62269
21                 0.07000          99615    AK                 99929
22                 0.07000          35014    AL                 36922
23                 0.07000          72047    AR                 72660
24                 0.07000          80018    CO                 80751
25                 0.07000          32003    FL                 34988
26                 0.07000          30011    GA                 39897
27                 0.07000          50001    IA                 52809
28                 0.07000          83638    ID                 83671
29                 0.07000          60002    IL                 62895
..                     ...            ...   ...                   ...
228                0.07400          80516    CO                 81649
229                0.05400          80530    CO                 81632
230                0.06700          80537    CO                 80549
231                0.05985          80544    CO                 80544
232                0.06850          80550    CO                 80551
233                0.06850          62010    IL                 62294
234                0.06400          80620    CO                 80620
235                0.07010          80631    CO                 80639
236                0.07880          80817    CO                 80817
237                0.08130          80819    CO                 80819
238                0.08730          80829    CO                 80829
239                0.07990          80863    CO                 80866
240                0.09400          81149    CO                 81225
241                0.08650          81201    CO                 81435
242                0.05650          81211    CO                 81236
243                0.07650          81242    CO                 81636
244                0.07350          81321    CO                 81321
245                0.07350          62059    IL                 62289
246                0.03300          81323    CO                 81335
247                0.04650          81403    CO                 81431
248                0.04150          81426    CO                 81430
249                0.09450          81427    CO                 81427
250                0.05450          81432    CO                 81432
251                0.08020          81501    CO                 81506
252                0.05270          81503    CO                 81646
253                0.08270          81521    CO                 81521
254                0.07270          81526    CO                 81526
255                0.04250          96704    HI                 96785
256                0.06250          60111    IL                 62996
257                0.07100          62025    IL                 62034

[258 rows x 4 columns]

In [146]:
allData.to_csv('allData.csv')